q1

In [5]:
# 1 a)
import numpy as np
arr = np.array([1, 2, 3, 6, 4, 5])
arr2 = np.flip(arr)
print(arr2)

[5 4 6 3 2 1]


In [6]:
# 1 b)
array1 = np.array([[1, 2, 3], [2, 4, 5], [1, 2, 3]])
arr2 = array1.flatten()
arr2

array([1, 2, 3, 2, 4, 5, 1, 2, 3])

In [12]:
# 1 c)
arr1 = np.array([[1, 2], [3, 4]]) 
arr2 = np.array([[1, 2], [3, 4]]) 
np.array_equal(arr1,arr2)

True

In [17]:
'''
1 (d) Find the most frequent value and their indice(s) in the following arrays: 
i. x = np.array([1,2,3,4,5,1,2,1,1,1]) 
ii. y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3, ]) 
'''
# i
x = np.array([1,2,3,4,5,1,2,1,1,1]) 
x1 = np.bincount(x)
max_occuring = x1.argmax()

indexes = np.where(x == max_occuring)[0]
print(f'max occuring is {max_occuring} and its indexes are {indexes}')

# ii
y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3, ]) 
y1 = np.bincount(y)
max_occuring = y1.argmax()

indexes = np.where(y == max_occuring)[0]
print(f'max occuring is {max_occuring} and its indexes are {indexes}')



max occuring is 1 and its indexes are [0 5 7 8 9]
max occuring is 1 and its indexes are [0 1 2]


In [27]:
# 1 e)
gfg = np.matrix('[4, 1, 9; 12, 3, 1; 4, 5, 6]')

totalsum = gfg.sum()
rowsum = gfg.sum(axis=0)
colsum = gfg.sum(axis=1)

print(f'totalsum is {totalsum} rowsum is {rowsum} colsum is {colsum}')

totalsum is 45 rowsum is [[20  9 16]] colsum is [[14]
 [16]
 [15]]


In [31]:
# 1 f)
n_array = np.array([[55, 25, 15],[30, 44, 2],[11, 45, 77]])

#i
diagsum = np.diagonal(n_array).sum()

#ii
eigval = np.linalg.eigvals(n_array)
print(f'eigon val is {eigval}')

#iii
eigvec = np.linalg.eig(n_array)
print(f'eigon vector is {eigvec}')

#iv
inv = np.linalg.inv(n_array)
print(f'inverse is {inv}')

#v
det = np.linalg.det(n_array)
print(f'determinant is {det}')

eigon val is [98.16835147 28.097044   49.73460452]
eigon vector is EigResult(eigenvalues=array([98.16835147, 28.097044  , 49.73460452]), eigenvectors=array([[ 0.4574917 ,  0.34637121, -0.15017693],
       [ 0.28447814, -0.72784061, -0.4852124 ],
       [ 0.84248058,  0.59184038,  0.8614034 ]]))
inverse is [[ 0.02404141 -0.00911212 -0.00444671]
 [-0.01667882  0.02966905  0.0024785 ]
 [ 0.00631287 -0.01603732  0.01217379]]
determinant is 137180.0000000001


In [35]:
# 1 g)

# Part i
p1 = np.array([[1, 2], [2, 3]])
q1 = np.array([[4, 5], [6, 7]])

# Matrix multiplication
product1 = np.dot(p1, q1)
print("Matrix multiplication ", product1)

# Covariance between flattened versions
cov1 = np.cov(p1.flatten(), q1.flatten())
print("Covariance matrix:\n", cov1)


# Part ii

p2 = np.array([[1, 2], [2, 3], [4, 5]])
q2 = np.array([[4, 5, 1], [6, 7, 2]])

# Matrix multiplication
product2 = np.dot(p2, q2)
print("Matrix multiplication \n", product2)

# Covariance between flattened versions
cov2 = np.cov(p2.flatten(), q2.flatten())
print("Covariance matrix:\n", cov2)


Matrix multiplication  [[16 19]
 [26 31]]
Covariance matrix:
 [[0.66666667 1.        ]
 [1.         1.66666667]]
Matrix multiplication 
 [[16 19  5]
 [26 31  8]
 [46 55 14]]
Covariance matrix:
 [[2.16666667 0.23333333]
 [0.23333333 5.36666667]]


In [40]:
# 1 h
from itertools import product

x = np.array([[2, 3, 4],
              [3, 2, 9]])

y = np.array([[1, 5, 0],
              [5, 10, 3]])

# Inner Product
inner = np.inner(x, y)
print("Inner Product ")
print(inner)

# Outer Product
outer = np.outer(x, y)
print("\n Outer Product ")
print(outer)

# Cartesian Product (row-wise combinations)
cartesian = np.array([np.concatenate((a, b)) for a, b in product(x, y)])
print("\nCartesian Product ")
print(cartesian)

Inner Product 
[[17 52]
 [13 62]]

 Outer Product 
[[ 2 10  0 10 20  6]
 [ 3 15  0 15 30  9]
 [ 4 20  0 20 40 12]
 [ 3 15  0 15 30  9]
 [ 2 10  0 10 20  6]
 [ 9 45  0 45 90 27]]

=== Cartesian Product ===
[[ 2  3  4  1  5  0]
 [ 2  3  4  5 10  3]
 [ 3  2  9  1  5  0]
 [ 3  2  9  5 10  3]]


q 2a

In [49]:
array = np.array([[1, -2, 3],[-4, 5, -6]])
#i
modulo = np.abs(array)
print(f'abs is \n {modulo}')

#ii
flat_percentiles = np.percentile(array, [25, 50, 75])
print("\nPercentiles (Flattened array):", flat_percentiles)

# Column-wise
col_percentiles = np.percentile(array, [25, 50, 75], axis=0)
print("\nColumn-wise percentiles:\n", col_percentiles)

# Row-wise
row_percentiles = np.percentile(array, [25, 50, 75], axis=1)
print("\nRow-wise percentiles:\n", row_percentiles)

#iii
# Mean
mean_flat = np.mean(array)
mean_col = np.mean(array, axis=0)
mean_row = np.mean(array, axis=1)

# Median
median_flat = np.median(array)
median_col = np.median(array, axis=0)
median_row = np.median(array, axis=1)

# Std. deviation
std_flat = np.std(array)
std_col = np.std(array, axis=0)
std_row = np.std(array, axis=1)

# Display

print(f"Flattened - Mean: {mean_flat}, Median: {median_flat}, Std: {std_flat}")
print(f"Column-wise - Mean: {mean_col}, Median: {median_col}, Std: {std_col}")
print(f"Row-wise - Mean: {mean_row}, Median: {median_row}, Std: {std_row}")

abs is 
 [[1 2 3]
 [4 5 6]]

Percentiles (Flattened array): [-3.5 -0.5  2.5]

Column-wise percentiles:
 [[-2.75 -0.25 -3.75]
 [-1.5   1.5  -1.5 ]
 [-0.25  3.25  0.75]]

Row-wise percentiles:
 [[-0.5 -5. ]
 [ 1.  -4. ]
 [ 2.   0.5]]
Flattened - Mean: -0.5, Median: -0.5, Std: 3.8622100754188224
Column-wise - Mean: [-1.5  1.5 -1.5], Median: [-1.5  1.5 -1.5], Std: [2.5 3.5 4.5]
Row-wise - Mean: [ 0.66666667 -1.66666667], Median: [ 1. -4.], Std: [2.05480467 4.78423336]


q 2b

In [50]:
a = np.array([-1.8, -1.6, -0.5, 0.5,1.6, 1.8, 3.0])

# Floor: largest integer ≤ value
floor_vals = np.floor(a)

# Ceil: smallest integer ≥ value
ceil_vals = np.ceil(a)

# Truncated: remove fractional part toward zero
trunc_vals = np.trunc(a)

# Rounded: to nearest integer (ties to even)
round_vals = np.round(a)

# Display results
print("Original array:      ", a)
print("Floor values:        ", floor_vals)
print("Ceiling values:      ", ceil_vals)
print("Truncated values:    ", trunc_vals)
print("Rounded values:      ", round_vals)

Original array:       [-1.8 -1.6 -0.5  0.5  1.6  1.8  3. ]
Floor values:         [-2. -2. -1.  0.  1.  1.  3.]
Ceiling values:       [-1. -1. -0.  1.  2.  2.  3.]
Truncated values:     [-1. -1. -0.  0.  1.  1.  3.]
Rounded values:       [-2. -2. -0.  0.  2.  2.  3.]


q3

In [51]:
# Part (a)
array_a = np.array([10, 52, 62, 16, 16, 54, 453])

# i. Sorted array
sorted_array = np.sort(array_a)

# ii. Indices of sorted array
sorted_indices = np.argsort(array_a)

# iii. 4 smallest elements
smallest_4 = sorted_array[:4]

# iv. 5 largest elements
largest_5 = sorted_array[-5:]


print("Original array:           ", array_a)
print("i. Sorted array:          ", sorted_array)
print("ii. Indices of sorted:    ", sorted_indices)
print("iii. 4 smallest elements: ", smallest_4)
print("iv. 5 largest elements:   ", largest_5)

# Part (b)
array_b = np.array([1.0, 1.2, 2.2, 2.0, 3.0, 2.0])

# i. Integer elements only
integer_elements = array_b[array_b == array_b.astype(int)]

# ii. Float (non-integer) elements only
float_elements = array_b[array_b != array_b.astype(int)]


print("Original array:             ", array_b)
print("i. Integer elements only:   ", integer_elements)
print("ii. Float elements only:    ", float_elements)

Original array:            [ 10  52  62  16  16  54 453]
i. Sorted array:           [ 10  16  16  52  54  62 453]
ii. Indices of sorted:     [0 3 4 1 5 2 6]
iii. 4 smallest elements:  [10 16 16 52]
iv. 5 largest elements:    [ 16  52  54  62 453]
Original array:              [1.  1.2 2.2 2.  3.  2. ]
i. Integer elements only:    [1. 2. 3. 2.]
ii. Float elements only:     [1.2 2.2]


q 4

In [26]:
from PIL import Image, ImageFile
import numpy as np

ImageFile.LOAD_TRUNCATED_IMAGES = True

def img_to_array(path):
    try:
        img = Image.open(path)
        img_arr = np.array(img)

        if img_arr.ndim == 2:
            print("Grayscale image detected")
            np.savetxt("image_grayscale.txt", img_arr, fmt='%d')
            return "grayscale"

        elif img_arr.ndim == 3:
            print("RGB image detected")
            flat = img_arr.reshape(-1, img_arr.shape[2])
            np.savetxt("image_rgb.txt", flat, fmt='%d')
            return "rgb"

        else:
            print("Image format not recognized")
            return None

    except Exception as e:
        print("Error:", e)
        return None

image_type = img_to_array("scorpio.jpg")

# Load the saved file based on type
if image_type == "grayscale":
    gray = np.loadtxt("image_grayscale.txt", dtype=int)
    print("Loaded grayscale shape:", gray.shape)
    print(gray[:5])  # Print only a part

elif image_type == "rgb":
    rgb = np.loadtxt("image_rgb.txt", dtype=int)
    print("Loaded RGB shape:", rgb.shape)
    print(rgb[:5])  # Print only a part

else:
    print("Could not load the saved image data.")


RGB image detected
Loaded RGB shape: (921600, 3)
[[ 89  94 100]
 [ 89  94 100]
 [ 89  94 100]
 [ 89  94 100]
 [ 89  94 100]]
